# Use the official MySQL 8.0 image as the base image
FROM postgres:latest

EXPOSE 5432

## Mysql

# ENV MYSQL_ROOT_PASSWORD=password
# ENV MYSQL_DATABASE=swole
# ENV MYSQL_CHARSET=utf8
# ENV MYSQL_COLLATION=utf8_general_ci

## Postgres
ENV POSTGRES_USER=postico
ENV POSTGRES_PASSWORD=pw
ENV POSTGRES_DB=swole
